### ISSUE TITLE
How to setup example

### ISSUE THREAD

**Issue by Grandpa-G** [TUM-E21-ThinFilms/Edwards-STP-iX455#1]
Could you give me a few lines of how to just do a simple command? Thanks.

**Comment by TUM-E21-ThinFilms** [comment]
I added a section in the README. 

Note that this package hasn't been updated for a while and it might not be python 3 compatible (I haven't checked it yet). Also it might not support all capabilities of the edwards stp-ix455, but the basic operation modes are working.

**Comment by Grandpa-G** [comment]
Thanks for the update. You are correct, it won’t run with Python3. There are number of changes that have to be made.
